helper_words: is, are, can, do, be, have, has, had, was, will, would, should, we, a, an, the, and, or, also, as, all, of, this, these, there, no, if, in
categories_file_path: src/main/resources/categories.json